fixing visual studio build
dlidstrom/Duplo pull request #31
Opened 2021-03-09 03:25 UTC by tyler97

Fixed typo from previous commit.
Added files that weren't being included in visual studio project.
Disabled warning 4146
Changed auto to auto& to avoid extra copies.
Build should work on with Visual Studio now.

2021-03-09 20:31 UTC, dlidstrom commented on src/SourceLine.cpp
>  #include <algorithm>
Interesting, so <iterator> is included by <algorithm> by both gcc and clang. I think you can remove the #ifdef as this header really should be included on all platforms.

2021-03-09 20:34 UTC, dlidstrom commented on src/SourceLine.cpp
> -
Can you put these on the line under? See SourceFile.cpp. Thanks.

2021-03-09 20:34 UTC, dlidstrom requested changes
Minor fixes needed.

2021-03-21 18:45 UTC, dlidstrom commented
Hi @tyler97 any chance you can finish this?

2021-03-22 15:21 UTC, tyler97 commented
Hi @dlidstrom , yes I'll try to finish it this week, been busy moving and doing some work around the house so hadn't had a chance to finish it earlier. Thanks!

2021-03-26 10:52 UTC, DanielLidstromTicket commented
Looks good to me, I can merge if you feel you're done.

2021-03-26 10:54 UTC, dlidstrom commented
Looks good to me, I can merge if you feel you're done.

2021-03-26 10:55 UTC, merged